/**
 * @fileoverview Node.js version of the modelMaps.ts file.
 * This file contains the model mappings for the validation scripts.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/sync-model-maps.js
 * Generated at: 2026-04-15T06:39:37.967Z
 */

// Model map from TypeScript source
const MODEL_MAP = {};

// Models list from TypeScript source
const MODELS = {};

/**
 * Get API name for a model key
 * @param {string} key Model key
 * @returns {string} API name
 */
function getApiNameFromKey(key) {
  const model = MODEL_MAP[key];
  return model ? model.apiName : key;
}

/**
 * Get model mapping for a key
 * @param {string} key Model key
 * @returns {object|undefined} Model mapping
 */
function getModelMapping(key) {
  return MODEL_MAP[key];
}

/**
 * Check if a model supports tool calling
 * @param {string} modelKey Model key
 * @returns {boolean} Whether the model supports tool calling
 */
function supportsToolCalling(modelKey) {
  const model = MODEL_MAP[modelKey];
  return model ? model.supportsToolCalling || false : false;
}

module.exports = {
  MODEL_MAP,
  MODELS,
  getApiNameFromKey,
  getModelMapping,
  supportsToolCalling
};
